<?php

/**
 * @file
 * Domain Access CiviCRM module.
 */

/**
 * Assign newly created CiviCRM contacts to their domain.
 */
function domain_civicrm_civicrm_post($op, $object_name, $object_id, &$object_ref) {
  if ($object_name == 'UFMatch' && $op == 'create') {
    // We need the uid.
    $uid = $object_ref->uf_id;
    // And the domain_id
    $domain = domain_resolve_host();
    $domain_id = $domain['domain_id'];

    // Then need to insert into domain_editor
    $query = db_insert('domain_editor')
      ->fields(array(
        'uid' => $uid,
        'domain_id' => $domain_id,
      )
      );
    $query->execute();
  }
}
