<?php

/**
 * @file
 * Domain Access CiviCRM module.
 */

/**
 * Assign newly created CiviCRM contacts to their domain.
 */
function domain_civicrm_civicrm_post($op, $object_name, $object_id, &$object_ref) {
  if ($object_name == 'UFMatch' && $op == 'create') {
    // We need the uid.
    $uid = $object_ref->uf_id;
    // And the domain_id
    $domain = domain_resolve_host();
    $domain_id = $domain['domain_id'];

    // Then need to 'merge' into domain_editor (so it works if creating users from Drupal admin)
	// -- the key() method also sets the 'insert' part of the query, but leaves the 'update' blank
	// -- https://api.drupal.org/api/drupal/includes!database!query.inc/function/MergeQuery%3A%3Akey/7.x
    $query = db_merge('domain_editor')
      ->key(array(
        'uid' => $uid,
        'domain_id' => $domain_id,
      ));
    $query->execute();
  }
}
